name: Triggers

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    types:
      - opened
      - synchronize


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GREETING: "Hello"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print the statement
        run: echo "$GREETING" 
